/** Mirrors only the public member_dashboard DTOs. Unknown fields fail closed. */
import {z} from 'zod';
const id=z.string().min(1).max(128), short=z.string().max(256), text=z.string().max(4000);
const epoch=z.number().finite().nullable(), url=z.string().max(2048).nullable();
export const sections=['analysis','sec','options','em_daily','em_weekly'] as const;
export const features=['feed','setups',...sections,'assistant'] as const;
export type Section=typeof sections[number];
export type Feature=typeof features[number];
export const labels:Record<Feature,string>={feed:'Analyst calls',setups:'Trade setups',analysis:'Custom Stock Analysis',sec:'SEC Filings',options:'Options Activity',em_daily:'Daily Expected Move',em_weekly:'Weekly Expected Move',assistant:'Market Assistant'};
const metric=z.strictObject({value:z.number().finite().nullable(),unit:short,method:short});
const context=z.strictObject({name:z.enum(['net_gamma','gamma_flip','iv_skew','risk']),metric,observed_at:epoch,source_id:id,source_version:id});
const evidence=z.strictObject({id,source_id:id,source_version:id,observed_at:epoch,url,excerpt:text,research_only:z.boolean()});
const direction=z.enum(['bullish','bearish','neutral','unclear']);
const analysis=z.strictObject({kind:z.literal('analysis'),summary:text,direction,score:metric.nullable(),catalysts:z.array(text).max(50),conflicts:z.array(text).max(50),levels:z.array(z.strictObject({label:short,price:metric,note:text.nullable().optional()})).max(50),risk_metrics:z.array(metric).max(50),context_metrics:z.array(context).max(20),horizons:z.array(z.strictObject({label:z.enum(['week','month','year']),low:metric.nullable(),high:metric.nullable(),middle:metric.nullable().optional(),note:text.nullable().optional()})).max(3).optional()});
const sec=z.strictObject({kind:z.literal('sec'),coverage:z.enum(['complete','partial']),filings:z.array(z.strictObject({accession:id,form:short,filed_at:epoch,title:short,summary:text,url,detail_status:z.enum(['ok','unavailable','not_requested'])})).max(200),insiders:z.array(z.strictObject({accession:id,summary:text,conviction:z.enum(['routine','conviction','unknown']),transaction_value:metric.nullable()})).max(200),warning:text.nullable()});
const options=z.strictObject({kind:z.literal('options'),contracts:z.array(z.strictObject({symbol:short,expiry:short,side:z.enum(['call','put']),strike:metric,volume:metric.nullable(),open_interest:metric.nullable(),premium:metric.nullable(),observed_at:epoch})).max(200),call_volume:metric.nullable(),put_volume:metric.nullable(),put_call_ratio:metric.nullable(),call_premium:metric.nullable(),put_premium:metric.nullable(),context_metrics:z.array(context).max(20)});
const move=z.strictObject({kind:z.literal('move'),horizon:z.enum(['daily','weekly']),spot:metric.nullable(),expiry:short.nullable(),ranges:z.array(z.strictObject({method:short,lower:metric.nullable(),upper:metric.nullable(),expected_move:metric.nullable()})).max(10),quote_times:z.array(z.strictObject({source_id:id,observed_at:epoch,input_kind:z.enum(['call','put','underlying','selection','history']).nullable()})).max(20),chart_asset_id:id.nullable(),context_metrics:z.array(context).max(20)});
const section=z.strictObject({section:z.enum(sections),status:z.enum(['queued','running','completed','unavailable','failed']),job_id:id.nullable(),result_id:id.nullable(),observed_at:epoch,computed_at:epoch,valid_until:epoch,stale:z.boolean(),analysis_version:id,evidence:z.array(evidence).max(200),payload:z.discriminatedUnion('kind',[analysis,sec,options,move]).nullable(),message:text.nullable(),attributions:z.array(short).max(200),delay_seconds:z.number().finite().nonnegative()}).refine(x=>!x.payload || (x.section.startsWith('em_')?x.payload.kind==='move'&&x.payload.horizon===(x.section==='em_daily'?'daily':'weekly'):x.payload.kind===x.section));
export const researchSchema=z.strictObject({id,report_id:id,ticker:z.string().max(16),sections:z.partialRecord(z.enum(sections),section)}).refine(x=>Object.entries(x.sections).every(([key,value])=>key===value.section));
const featureState=z.strictObject({enabled:z.boolean(),version:z.number().int().positive()});
export const memberSchema=z.strictObject({id:z.string(),username:z.string(),role:z.enum(['member','admin'])});
export const currentMemberSchema=memberSchema.extend({features:z.record(z.enum(features),featureState)});
export const loginSchema=z.strictObject({member:memberSchema,csrf_token:z.string().max(128)});
export const csrfSchema=z.strictObject({token:z.string().max(128)});
const source=z.enum(['analyst_views','signal_events','alert_history','decision_snapshots','ticker_signals','research_sections','swarm_alerts']);
const feedPayload=z.strictObject({ticker:z.string().max(16),direction,excerpt:text,score:z.number().finite().nullable(),price:z.number().finite().nullable(),research_only:z.literal(true),entry:z.number().finite().nullable(),target:z.number().finite().nullable(),invalidation:z.number().finite().nullable(),attributions:z.array(z.string().max(1536)).max(200),evidence:z.array(evidence).max(200)});
export const upsertSchema=z.strictObject({operation:z.literal('upsert'),id,content_version:id,summary_version:id,source:source.nullable(),payload:feedPayload,observed_at:epoch,projected_at:z.number().finite(),published_at:epoch,stale:z.boolean(),delay_seconds:z.number().finite().nonnegative()});
export const freshnessSchema=z.strictObject({source,status:z.enum(['available','stale','unavailable']),checked_at:epoch,succeeded_at:epoch});
export const feedSchema=z.strictObject({records:z.array(z.discriminatedUnion('operation',[upsertSchema,z.strictObject({operation:z.literal('delete'),id})])).max(100),cursor:z.string().max(4096),snapshot:z.boolean(),has_more:z.boolean(),sources:z.array(freshnessSchema).max(9)});
export type ResearchRequest=z.infer<typeof researchSchema>;
export type SectionResult=z.infer<typeof section>;
export type CurrentMember=z.infer<typeof currentMemberSchema>;
export type Metric=z.infer<typeof metric>;
export type Evidence=z.infer<typeof evidence>;
export type ContextMetric=z.infer<typeof context>;
export type MovePayload=z.infer<typeof move>;
export type FeedCard=z.infer<typeof upsertSchema>;
export type FeedPage=z.infer<typeof feedSchema>;
export type SourceFreshness=z.infer<typeof freshnessSchema>;

const cursor=z.string().max(4096).nullable();
const reportRef=z.strictObject({id,created_at:z.number().finite(),ticker:z.string().max(16).nullable()});
const annotation=z.strictObject({evidence_id:id,source_id:id,source_version:id,status:z.enum(['retracted','unavailable']),recorded_at:epoch});
export const reportPageSchema=z.strictObject({items:z.array(reportRef).max(100),cursor});
export const savedReportSchema=reportRef.extend({version:z.number().int().positive().nullable(),saved_at:epoch,finalized:z.boolean(),availability:z.enum(['available','pending','unavailable']),sections:z.partialRecord(z.enum(sections),section),annotations:z.partialRecord(z.enum(sections),z.array(annotation).max(200))}).refine(x=>Object.entries(x.sections).every(([key,value])=>key===value.section));
export const conversationRef=z.strictObject({id,title:short,created_at:z.number().finite(),version:z.number().int().positive()});
export const conversationPageSchema=z.strictObject({items:z.array(conversationRef).max(100),cursor});
const savedMessage=z.strictObject({id,role:z.enum(['user','assistant']),created_at:z.number().finite(),text:text.nullable(),evidence:z.array(evidence).max(200),availability:z.enum(['available','unavailable']),annotations:z.array(annotation).max(200)});
export const savedConversationSchema=conversationRef.extend({messages:z.array(savedMessage).max(100),cursor});
export type ReportPage=z.infer<typeof reportPageSchema>;
export type SavedReport=z.infer<typeof savedReportSchema>;
export type ConversationPage=z.infer<typeof conversationPageSchema>;
export type SavedConversation=z.infer<typeof savedConversationSchema>;
export const assistantRunSchema=z.strictObject({id,conversation_id:id,input_message_id:id.nullable(),status:z.enum(['queued','running','completed','unavailable','failed']),ticker_context:z.string().max(16).nullable(),created_at:z.number().finite(),finished_at:epoch,message:short.nullable(),response_message_id:id.nullable(),model_id:id.nullable(),input_tokens:z.number().int().nonnegative().nullable(),output_tokens:z.number().int().nonnegative().nullable(),cost:z.number().finite().nonnegative().nullable()});
export type AssistantRun=z.infer<typeof assistantRunSchema>;
export type ConversationRef=z.infer<typeof conversationRef>;

const plan=z.strictObject({direction:z.enum(['long','short','neutral']),entry_low:z.number().finite().nullable(),entry_high:z.number().finite().nullable(),stop:z.number().finite().nullable(),targets:z.array(z.number().finite()).max(3),computed_at:z.number().finite()});
const group=z.strictObject({analysts:z.number().int().min(2),span:z.string().max(32),calls:z.array(z.strictObject({analyst:z.string().max(40),view:z.enum(['bullish','bearish','unclear']),reason:text})).max(20)});
export const latestCardSchema=z.strictObject({id,ticker:z.string().max(16),direction,text,url,score:z.number().finite().nullable(),price:z.number().finite().nullable(),observed_at:z.number().finite(),plan:plan.nullable(),group:group.nullable().optional()});
export const latestPageSchema=z.strictObject({cards:z.array(latestCardSchema).max(50)});
export type LatestCard=z.infer<typeof latestCardSchema>;
export type TradePlan=z.infer<typeof plan>;
