'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
import type {MovePayload} from '@/lib/contracts';
import {clearAccess} from '@/lib/api';
import {formatExpiry,formatPacific} from '@/lib/time';
import {ContextMetrics,MetricItem} from './research-details';
function OwnedChart({id,horizon}:{id:string;horizon:string}){const [url,setUrl]=useState<string|null>(null);useEffect(()=>{const abort=new AbortController();let objectUrl:string|undefined;void(async()=>{try{const response=await fetch('/api/v1/assets/'+encodeURIComponent(id),{credentials:'same-origin',cache:'no-store',signal:abort.signal});if(response.status===401)clearAccess();if(!response.ok||response.headers.get('content-type')?.split(';')[0]!=='image/png')return;const blob=await response.blob();if(!abort.signal.aborted&&blob.size<=2_000_000){objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}}catch{}})();return()=>{abort.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[id]);return url?<Image unoptimized src={url} alt={`${horizon} expected move chart; numerical ranges follow`} width={760} height={170}/>:<p className="muted">Chart unavailable</p>}
export function ExpectedMove({payload}:{payload:MovePayload}){const horizon=payload.horizon==='daily'?'Daily':'Weekly';return <><p className="notice">Estimated range, not a trade target.</p>{payload.chart_asset_id?<OwnedChart key={payload.chart_asset_id} id={payload.chart_asset_id} horizon={horizon}/>:<p className="muted">Chart unavailable</p>}<dl className="metric-grid"><MetricItem label="Spot reference" metric={payload.spot}/><div className="metric"><dt>Option expiry</dt><dd>{formatExpiry(payload.expiry)}</dd><small>Calendar date</small></div></dl>{payload.ranges.map((range,i)=><div key={i}><h3>{range.method}</h3><dl className="metric-grid"><MetricItem label="Lower estimate" metric={range.lower}/><MetricItem label="Upper estimate" metric={range.upper}/><MetricItem label="Expected move" metric={range.expected_move}/></dl></div>)}<details className="evidence"><summary>Actual quote input times</summary>{payload.quote_times.map((q,i)=><p key={i}>{q.input_kind??'Input type unavailable'} · {q.source_id} · {formatPacific(q.observed_at)}</p>)}</details><ContextMetrics items={payload.context_metrics}/></>}
