import {labels,type SectionResult} from '@/lib/contracts';
import {formatExpiry,formatPacific} from '@/lib/time';
import {ContextMetrics,EvidenceList,MetricItem,SafeLink,Value} from './research-details';
import {ExpectedMove} from './expected-move';
export function ResearchSection({result}:{result:SectionResult}){const p=result.payload;return <section className="card report-section" id={result.section}><div className="section-heading"><h2>{labels[result.section]}</h2><span role="status" data-testid={result.section+'-status'} className={'status status-'+result.status}>{result.status[0].toUpperCase()+result.status.slice(1)}</span></div><div className="metadata"><span>Observed {formatPacific(result.observed_at)}</span><span>Computed {formatPacific(result.computed_at)}</span></div><div className="disclosures">{result.stale&&<span className="tag">Stale observation</span>}{result.delay_seconds>0&&<span className="tag">Source delay: {result.delay_seconds} seconds</span>}<span>Research only</span></div>
 {result.message&&<p className="notice">{result.message}</p>}{!p&&<p className="muted">{['queued','running'].includes(result.status)?'This section is being prepared. Other results appear independently.':'No permitted result is available for this section.'}</p>}
 {p?.kind==='analysis'&&<><p className="report-summary">{p.summary}</p><dl className="metric-grid"><div className="metric"><dt>Direction</dt><dd className="capitalize">{p.direction}</dd></div><MetricItem label="Research score" metric={p.score}/>{p.levels.map((l,i)=><MetricItem key={i} label={l.label} metric={l.price}/>)}</dl>{p.catalysts.length>0&&<><h3>Catalysts</h3><ul>{p.catalysts.map((c,i)=><li key={i}>{c}</li>)}</ul></>}{p.conflicts.length>0&&<><h3>Conflicting evidence</h3><ul>{p.conflicts.map((c,i)=><li key={i}>{c}</li>)}</ul></>}<dl className="metric-grid">{p.risk_metrics.map((m,i)=><MetricItem key={i} label="Risk metric" metric={m}/>)}</dl><ContextMetrics items={p.context_metrics}/></>}
 {p?.kind==='sec'&&<><p>Coverage: <strong>{p.coverage}</strong></p>{p.warning&&<p className="notice">{p.warning}</p>}{p.filings.length===0&&<p>No filings supplied.</p>}{p.filings.map(f=><article key={f.accession} className="filing"><div className="section-heading"><h3><SafeLink url={f.url}>{f.form} · {f.title}</SafeLink></h3><span className="small">{formatPacific(f.filed_at)}</span></div><p>{f.summary}</p><small>Detail: {f.detail_status.replaceAll('_',' ')} · {f.accession}</small></article>)}{p.insiders.length>0&&<><h3>Insider summaries</h3>{p.insiders.map(i=><div key={i.accession}><p>{i.summary} · {i.conviction}</p><p>Transaction value: <Value metric={i.transaction_value}/></p></div>)}</>}</>}
 {p?.kind==='options'&&<><dl className="metric-grid"><MetricItem label="Call volume" metric={p.call_volume}/><MetricItem label="Put volume" metric={p.put_volume}/><MetricItem label="Put / call ratio" metric={p.put_call_ratio}/><MetricItem label="Call premium" metric={p.call_premium}/><MetricItem label="Put premium" metric={p.put_premium}/></dl><h3>Observed contracts</h3>{p.contracts.length===0&&<p>No contract observations supplied.</p>}{p.contracts.map((c,i)=><article className="contract" key={i}><h4>{c.symbol} · {c.side}</h4><p>Expiry {formatExpiry(c.expiry)} · Observed {formatPacific(c.observed_at)}</p><dl className="metric-grid"><MetricItem label="Strike" metric={c.strike}/><MetricItem label="Volume" metric={c.volume}/><MetricItem label="Open interest" metric={c.open_interest}/><MetricItem label="Premium" metric={c.premium}/></dl></article>)}<ContextMetrics items={p.context_metrics}/></>}
 {p?.kind==='move'&&<ExpectedMove payload={p}/>}<EvidenceList items={result.evidence}/>{result.attributions.length>0&&<div className="attributions">{result.attributions.map((a,i)=><p key={i}>{a}</p>)}</div>}<p className="small muted">Cache valid until {formatPacific(result.valid_until)} · Analysis {result.analysis_version}</p></section>}
